name: Metrics

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: lowlighter/metrics@v3
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: RaviKurane17
          filename: github-metrics.svg

          base: header, activity, community, repositories, metadata

          plugin_languages: yes
          plugin_isocalendar: yes
          plugin_lines: yes
          plugin_stars: yes
          plugin_topics: yes

          config_timezone: Asia/Kolkata
